from typing import Any, Callable

def hash_to_G2(message: bytes, DST: bytes, hash_function: Callable[..., Any]) -> Any: ...
def expand_message_xmd(message: bytes, DST: bytes, len_in_bytes: int, hash_function: Callable[..., Any]) -> bytes: ...
