// SPDX-License-Identifier: CC0-1.0
pragma solidity ^0.8.28;

import "forge-std/Test.sol";
import "../src/NozkVaultV2.sol";

/**
 * @title NozkVaultV2 Test Suite
 * @notice Tests for BLS12-381 standard scheme (PK=G1, Sig=G2).
 *         Requires EIP-2537 precompile support (Pectra / Prague EVM).
 *
 *         Test vectors generated by nozk_py/generate_vectors.py use:
 *           chain_id  = 31337
 *           contract  = 0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f
 *         This address is the deterministic CREATE result from Forge's
 *         test contract (0x7FA9...) at nonce 1.
 */
contract NozkVaultV2Test is Test {
    address deployer = address(0xDEAD);
    address mintAuth = address(0xBEEF);

    // Expected contract address for EIP-712 tests (CREATE from test contract, nonce 1)
    address constant VECTOR_CONTRACT = 0x5615dEB798BB3E4dFa0139dFa1b3D433Cc23b72f;

    // -- Test vector data (loaded in setUp) --
    string vectorSuite;
    string[] keypairDirs;
    uint256[] tokenIndices;

    function setUp() public {
        vectorSuite = "../test_vectors";
        string memory manifest = vm.readFile(string.concat(vectorSuite, "/manifest.json"));
        keypairDirs = vm.parseJsonStringArray(manifest, ".keypairs");
        tokenIndices = vm.parseJsonUintArray(manifest, ".indices");
    }

    // =========================================================================
    //  Helpers
    // =========================================================================

    function _tokenFile(string memory kpDir, uint256 idx) internal view returns (string memory) {
        return string.concat(vectorSuite, "/", kpDir, "/token_", vm.toString(idx), ".json");
    }

    function _hexU256(string memory j, string memory path) internal pure returns (uint256) {
        return vm.parseUint(vm.parseJsonString(j, path));
    }

    function _loadPkMint(string memory j) internal pure returns (uint256[4] memory pk) {
        pk[0] = _hexU256(j, ".PK_MINT.x_hi");
        pk[1] = _hexU256(j, ".PK_MINT.x_lo");
        pk[2] = _hexU256(j, ".PK_MINT.y_hi");
        pk[3] = _hexU256(j, ".PK_MINT.y_lo");
    }

    function _loadG1(string memory j, string memory prefix) internal pure returns (uint256[4] memory p) {
        p[0] = _hexU256(j, string.concat(prefix, ".x_hi"));
        p[1] = _hexU256(j, string.concat(prefix, ".x_lo"));
        p[2] = _hexU256(j, string.concat(prefix, ".y_hi"));
        p[3] = _hexU256(j, string.concat(prefix, ".y_lo"));
    }

    function _loadG2(string memory j, string memory prefix) internal pure returns (uint256[8] memory p) {
        p[0] = _hexU256(j, string.concat(prefix, ".x_c0_hi"));
        p[1] = _hexU256(j, string.concat(prefix, ".x_c0_lo"));
        p[2] = _hexU256(j, string.concat(prefix, ".x_c1_hi"));
        p[3] = _hexU256(j, string.concat(prefix, ".x_c1_lo"));
        p[4] = _hexU256(j, string.concat(prefix, ".y_c0_hi"));
        p[5] = _hexU256(j, string.concat(prefix, ".y_c0_lo"));
        p[6] = _hexU256(j, string.concat(prefix, ".y_c1_hi"));
        p[7] = _hexU256(j, string.concat(prefix, ".y_c1_lo"));
    }

    /// @dev Deploy vault with vector's pkMint at the deterministic address.
    ///      Sets chainId to 31337 so the EIP-712 domain separator matches vectors.
    ///      MUST be the first CREATE in the calling test (nonce 1).
    function _deployVault(string memory tokenJson) internal returns (NozkVaultV2) {
        uint256[4] memory pk = _loadPkMint(tokenJson);
        vm.chainId(31337);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);
        assertEq(address(v), VECTOR_CONTRACT, "Vault must deploy at vector contract address");
        return v;
    }

    function _depositAnnounceReveal(NozkVaultV2 v, string memory j) internal {
        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");
        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        uint256[8] memory S_prime = _loadG2(j, ".S_PRIME");
        vm.prank(mintAuth);
        v.announce(depositId, S_prime);

        uint256[4] memory spendPub = _loadG1(j, ".REVEAL_TX.spend_pub_G1");
        uint256[8] memory S = _loadG2(j, ".REVEAL_TX.S_G2");
        v.reveal(spendPub, S);
    }

    // =========================================================================
    //  Deployment + basic state
    // =========================================================================

    function test_deployWithVectorPkMint() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);

        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);
        assertEq(v.mintAuthority(), mintAuth);
        assertEq(v.DENOMINATION(), 0.001 ether);

        for (uint256 i = 0; i < 4; i++) {
            assertEq(v.pkMint(i), pk[i]);
        }
    }

    function test_nullifierId() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        uint256[4] memory spendPub = _loadG1(j, ".SPEND_BLS.pub_G1");
        bytes32 expectedNId =
            bytes32(vm.parseUint(string.concat("0x", vm.parseJsonString(j, ".SPEND_BLS.nullifier_id"))));

        assertEq(v.nullifierId(spendPub), expectedNId);
    }

    // =========================================================================
    //  Deposit + Announce
    // =========================================================================

    function test_deposit() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        assertTrue(v.depositPending(depositId));
    }

    function test_deposit_revertsWrongValue() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        vm.expectRevert(NozkVaultV2.InvalidValue.selector);
        v.deposit{value: 0.002 ether}(depositId, B);
    }

    function test_announce() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");
        uint256[8] memory S_prime = _loadG2(j, ".S_PRIME");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        vm.prank(mintAuth);
        v.announce(depositId, S_prime);
        assertTrue(v.depositFulfilled(depositId));
    }

    function test_announce_revertsNotMintAuthority() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");
        uint256[8] memory S_prime = _loadG2(j, ".S_PRIME");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        vm.prank(address(0x999));
        vm.expectRevert(NozkVaultV2.NotMintAuthority.selector);
        v.announce(depositId, S_prime);
    }

    // =========================================================================
    //  Reveal (requires EIP-2537)
    // =========================================================================

    function test_reveal() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");
        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        uint256[8] memory S_prime = _loadG2(j, ".S_PRIME");
        vm.prank(mintAuth);
        v.announce(depositId, S_prime);

        uint256[4] memory spendPub = _loadG1(j, ".REVEAL_TX.spend_pub_G1");
        uint256[8] memory S = _loadG2(j, ".REVEAL_TX.S_G2");
        v.reveal(spendPub, S);

        bytes32 nId = v.nullifierId(spendPub);
        assertEq(uint256(v.nullifierState(nId)), uint256(NozkVaultV2.NullifierState.REVEALED));
    }

    // =========================================================================
    //  Full lifecycle: reveal + redeem with balance verification
    // =========================================================================

    function test_fullLifecycle_revealAndRedeem() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        NozkVaultV2 v = _deployVault(j);

        _depositAnnounceReveal(v, j);

        uint256[4] memory spendPub = _loadG1(j, ".REVEAL_TX.spend_pub_G1");
        bytes32 nId = v.nullifierId(spendPub);

        address recipient = vm.parseAddress(vm.parseJsonString(j, ".REDEEM_TX.recipient"));
        uint256[8] memory spendSig = _loadG2(j, ".REDEEM_TX.sigma_G2");
        uint256 deadline = vm.parseUint(vm.parseJsonString(j, ".REDEEM_TX.deadline"));

        uint256 balBefore = recipient.balance;
        v.redeem(recipient, spendSig, nId, deadline);

        assertEq(recipient.balance - balBefore, 0.001 ether);
        assertEq(uint256(v.nullifierState(nId)), uint256(NozkVaultV2.NullifierState.SPENT));
    }

    function test_eip712HashMatchesVector() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        NozkVaultV2 v = _deployVault(j);

        address recipient = vm.parseAddress(vm.parseJsonString(j, ".REDEEM_TX.recipient"));
        uint256 deadline = vm.parseUint(vm.parseJsonString(j, ".REDEEM_TX.deadline"));
        bytes32 expected = bytes32(vm.parseUint(string.concat("0x", vm.parseJsonString(j, ".REDEEM_TX.msg_hash"))));

        assertEq(v.redemptionMessageHash(recipient, deadline), expected);
    }

    // =========================================================================
    //  Aggregated reveal (single pairing for n tokens, same mint key)
    // =========================================================================

    function test_revealAggregated() public {
        string memory j0 = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j0);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        string memory aggFile = string.concat(vectorSuite, "/", keypairDirs[0], "/aggregation.json");
        string memory agg = vm.readFile(aggFile);
        uint256[] memory aggIndices = vm.parseJsonUintArray(agg, ".token_indices");

        // Deposit + announce each token individually
        for (uint256 i; i < aggIndices.length; i++) {
            string memory tj = vm.readFile(_tokenFile(keypairDirs[0], aggIndices[i]));
            address depositId = vm.parseAddress(vm.parseJsonString(tj, ".DEPOSIT_ID"));
            uint256[8] memory B = _loadG2(tj, ".B_BLINDED");
            uint256[8] memory S_prime = _loadG2(tj, ".S_PRIME");

            vm.deal(deployer, 1 ether);
            vm.prank(deployer);
            v.deposit{value: 0.001 ether}(depositId, B);
            vm.prank(mintAuth);
            v.announce(depositId, S_prime);
        }

        // Build spendPubs + load aggregated sigma from vector
        uint256 n = aggIndices.length;
        uint256[4][] memory spendPubs = new uint256[4][](n);
        for (uint256 i; i < n; i++) {
            spendPubs[i] = _loadG1(agg, string.concat(".AGGREGATED_REVEAL.spend_pubs_G1[", vm.toString(i), "]"));
        }
        uint256[8] memory sigma = _loadG2(agg, ".AGGREGATED_REVEAL.sigma_G2");

        v.revealAggregated(spendPubs, sigma);

        for (uint256 i; i < n; i++) {
            bytes32 nId = v.nullifierId(spendPubs[i]);
            assertEq(uint256(v.nullifierState(nId)), uint256(NozkVaultV2.NullifierState.REVEALED));
        }
    }

    // =========================================================================
    //  Batch reveal (individual pairing per token)
    // =========================================================================

    function test_revealBatch() public {
        string memory j0 = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j0);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        string memory aggFile = string.concat(vectorSuite, "/", keypairDirs[0], "/aggregation.json");
        string memory agg = vm.readFile(aggFile);
        uint256[] memory aggIndices = vm.parseJsonUintArray(agg, ".token_indices");
        uint256 n = aggIndices.length;

        // Deposit + announce
        for (uint256 i; i < n; i++) {
            string memory tj = vm.readFile(_tokenFile(keypairDirs[0], aggIndices[i]));
            address depositId = vm.parseAddress(vm.parseJsonString(tj, ".DEPOSIT_ID"));
            uint256[8] memory B = _loadG2(tj, ".B_BLINDED");
            uint256[8] memory S_prime = _loadG2(tj, ".S_PRIME");

            vm.deal(deployer, 1 ether);
            vm.prank(deployer);
            v.deposit{value: 0.001 ether}(depositId, B);
            vm.prank(mintAuth);
            v.announce(depositId, S_prime);
        }

        // Build arrays for revealBatch
        uint256[4][] memory spendPubs = new uint256[4][](n);
        uint256[8][] memory sigs = new uint256[8][](n);
        for (uint256 i; i < n; i++) {
            string memory tj = vm.readFile(_tokenFile(keypairDirs[0], aggIndices[i]));
            spendPubs[i] = _loadG1(tj, ".REVEAL_TX.spend_pub_G1");
            sigs[i] = _loadG2(tj, ".REVEAL_TX.S_G2");
        }

        v.revealBatch(spendPubs, sigs);

        for (uint256 i; i < n; i++) {
            bytes32 nId = v.nullifierId(spendPubs[i]);
            assertEq(uint256(v.nullifierState(nId)), uint256(NozkVaultV2.NullifierState.REVEALED));
        }
    }

    // =========================================================================
    //  Aggregated redeem (multi-pairing for n tokens, diff keys)
    // =========================================================================

    function test_redeemAggregated() public {
        string memory j0 = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        NozkVaultV2 v = _deployVault(j0);

        string memory aggFile = string.concat(vectorSuite, "/", keypairDirs[0], "/aggregation.json");
        string memory agg = vm.readFile(aggFile);
        uint256[] memory aggIndices = vm.parseJsonUintArray(agg, ".token_indices");
        uint256 n = aggIndices.length;

        // Deposit + announce + reveal each token
        for (uint256 i; i < n; i++) {
            string memory tj = vm.readFile(_tokenFile(keypairDirs[0], aggIndices[i]));
            _depositAnnounceReveal(v, tj);
        }

        // Load aggregated redeem data
        address recipient = vm.parseAddress(vm.parseJsonString(agg, ".AGGREGATED_REDEEM.recipient"));
        uint256[8] memory sigma = _loadG2(agg, ".AGGREGATED_REDEEM.sigma_G2");
        uint256 deadline = vm.parseUint(vm.parseJsonString(agg, ".AGGREGATED_REDEEM.deadline"));

        bytes32[] memory nIds = new bytes32[](n);
        for (uint256 i; i < n; i++) {
            uint256[4] memory spendPub =
                _loadG1(agg, string.concat(".AGGREGATED_REDEEM.spend_pubs_G1[", vm.toString(i), "]"));
            nIds[i] = v.nullifierId(spendPub);
        }

        uint256 balBefore = recipient.balance;
        v.redeemAggregated(recipient, sigma, nIds, deadline);

        assertEq(recipient.balance - balBefore, 0.001 ether * n);
        for (uint256 i; i < n; i++) {
            assertEq(uint256(v.nullifierState(nIds[i])), uint256(NozkVaultV2.NullifierState.SPENT));
        }
    }

    // =========================================================================
    //  Refund
    // =========================================================================

    function test_refund() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        uint256 balBefore = deployer.balance;
        vm.prank(deployer);
        v.refund(depositId);
        assertEq(deployer.balance - balBefore, 0.001 ether);
        assertFalse(v.depositPending(depositId));
    }

    function test_refund_revertsAfterAnnounce() public {
        string memory j = vm.readFile(_tokenFile(keypairDirs[0], tokenIndices[0]));
        uint256[4] memory pk = _loadPkMint(j);
        NozkVaultV2 v = new NozkVaultV2(pk, mintAuth);

        address depositId = vm.parseAddress(vm.parseJsonString(j, ".DEPOSIT_ID"));
        uint256[8] memory B = _loadG2(j, ".B_BLINDED");
        uint256[8] memory S_prime = _loadG2(j, ".S_PRIME");

        vm.deal(deployer, 1 ether);
        vm.prank(deployer);
        v.deposit{value: 0.001 ether}(depositId, B);

        vm.prank(mintAuth);
        v.announce(depositId, S_prime);

        vm.prank(deployer);
        vm.expectRevert(NozkVaultV2.NothingToRefund.selector);
        v.refund(depositId);
    }
}
