from typing import Any

FQ: Any
FQ2: Any
Z1: Any
Z2: Any
G1: Any
G2: Any

curve_order: int
field_modulus: int

def add(a: Any, b: Any) -> Any: ...
def eq(a: Any, b: Any) -> bool: ...
def multiply(a: Any, n: int) -> Any: ...
def neg(a: Any) -> Any: ...
def normalize(a: Any) -> Any: ...
def pairing(a: Any, b: Any) -> Any: ...
