"""Minimal type stubs for py_ecc.bn128 — fixes FQ.n and multiply() return types."""

from typing import Sequence, overload

class FQ:
    n: int
    def __init__(self, val: int) -> None: ...
    def __add__(self, other: "FQ") -> "FQ": ...
    def __sub__(self, other: "FQ") -> "FQ": ...
    def __mul__(self, other: "FQ") -> "FQ": ...
    def __neg__(self) -> "FQ": ...
    def __eq__(self, other: object) -> bool: ...

class FQ2:
    coeffs: tuple[FQ, FQ]
    def __init__(self, coeffs: Sequence[int | FQ]) -> None: ...
    def __add__(self, other: "FQ2") -> "FQ2": ...
    def __sub__(self, other: "FQ2") -> "FQ2": ...
    def __mul__(self, other: "FQ2") -> "FQ2": ...
    def __neg__(self) -> "FQ2": ...
    def __eq__(self, other: object) -> bool: ...

Point2D = tuple[FQ, FQ]
Point2D_FQ2 = tuple[FQ2, FQ2]

G1: Point2D
G2: Point2D_FQ2
Z1: Point2D
Z2: Point2D_FQ2

b: FQ
b2: FQ2
curve_order: int
field_modulus: int

@overload
def multiply(pt: Point2D, n: int) -> Point2D: ...
@overload
def multiply(pt: Point2D_FQ2, n: int) -> Point2D_FQ2: ...
def add(p1: Point2D, p2: Point2D) -> Point2D: ...
def neg(pt: Point2D) -> Point2D: ...
def is_on_curve(pt: Point2D | Point2D_FQ2, b_val: FQ | FQ2) -> bool: ...
def pairing(Q: Point2D_FQ2, P: Point2D) -> FQ: ...
