#!/usr/bin/env python3
"""Generate markdown index files from YAML source catalogs.

Reads papers/sources.yaml, standards/rfcs/sources.yaml, and standards/eips/sources.yaml
to produce README.md index files with summaries, relevance, and keywords.

This is the ONLY way to update the markdown indexes — never edit them by hand.
Edit the YAML sources instead and re-run this script.

Usage:
    uv run generate_indexes.py           # generate all indexes
    uv run generate_indexes.py --check   # verify indexes are up to date (CI mode)
"""

from __future__ import annotations

import argparse
import sys
import textwrap
from pathlib import Path

import yaml

DOCS_SRC = Path(__file__).parent / "src"
PAPERS_DIR = DOCS_SRC / "papers"
STANDARDS_DIR = DOCS_SRC / "standards"
RFCS_DIR = STANDARDS_DIR / "rfcs"
EIPS_DIR = STANDARDS_DIR / "eips"
BIPS_DIR = STANDARDS_DIR / "bips"

GENERATED_HEADER = """\
<!-- DO NOT EDIT — generated by generate_indexes.py from sources.yaml -->
<!-- To update: edit sources.yaml, then run: uv run generate_indexes.py -->

"""


def load_yaml(path: Path) -> list[dict]:
    """Load documents list from a YAML sources file."""
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    return data.get("documents", [])


def best_link(doc: dict, base_dir: str = "") -> str:
    """Return the best link for a document: generated .md > .md > .html > .pdf > .txt."""
    prefix = f"{base_dir}/" if base_dir else ""

    # Check for generated markdown
    generated = doc.get("generated_md")
    if generated:
        return f"{prefix}{generated}"

    local = doc.get("local_file", "")
    extras = doc.get("local_files_extra", [])
    local_files_list = doc.get("local_files", [])

    # Check for existing .md in extras
    for f in extras:
        if f.endswith(".md"):
            return f"{prefix}{f}"

    # Check for .md in local_files list
    for f in local_files_list:
        if f.endswith(".md") and not f.endswith(".bib"):
            return f"{prefix}{f}"

    # Fall back to the primary local file
    if local:
        return f"{prefix}{local}"

    # For standards with local_files list, prefer .md > .txt
    for ext in [".md", ".txt"]:
        for f in local_files_list:
            if f.endswith(ext) and not f.endswith(".bib"):
                return f"{prefix}{f}"

    return ""


def format_keywords(doc: dict) -> str:
    """Format keywords as inline tags."""
    keywords = doc.get("keywords", [])
    if not keywords:
        return ""
    return " · ".join(f"`{k}`" for k in keywords[:6])


def generate_papers_readme(docs: list[dict]) -> str:
    """Generate papers/README.md from papers sources.yaml."""
    lines = [GENERATED_HEADER]
    lines.append("# Research Papers\n")
    lines.append(
        "Local copies of research papers referenced by the NozKash protocol.\n"
        "See [sources.yaml](sources.yaml) for machine-readable metadata.\n"
    )

    # Group by section comments in the YAML (using provenance)
    core = [d for d in docs if not d.get("provenance")]
    forward = [d for d in docs if d.get("provenance") == "forward-citation"]

    # Core papers
    lines.append("## Core Collection\n")
    for doc in core:
        link = best_link(doc)
        title = doc.get("title", "Untitled")
        authors = doc.get("authors", [])
        year = doc.get("year", "")
        author_str = ", ".join(authors) if authors else ""

        lines.append(f"### [{title}]({link})\n")
        if author_str:
            lines.append(f"**{author_str}** ({year}) — {doc.get('venue', '')}\n")
        else:
            lines.append(f"({year}) — {doc.get('venue', '')}\n")

        abstract = doc.get("abstract", "").strip()
        if abstract:
            lines.append(f"{abstract}\n")

        relevance = doc.get("relevance", doc.get("notes", "")).strip()
        if relevance:
            lines.append(f"**NozKash relevance:** {relevance}\n")

        kw = format_keywords(doc)
        if kw:
            lines.append(f"**Keywords:** {kw}\n")

        key_sections = doc.get("key_sections", [])
        if key_sections:
            lines.append("**Key sections:**\n")
            for s in key_sections:
                lines.append(f"- {s}")
            lines.append("")

        lines.append("---\n")

    # Forward citations
    if forward:
        lines.append("## Forward Citations\n")
        lines.append(
            "*Discovered via literature survey of the core collection. "
            "See [forward-citations.md](../forward-citations.md) for the full triage log.*\n"
        )

        for doc in forward:
            link = best_link(doc)
            title = doc.get("title", "Untitled")
            authors = doc.get("authors", [])
            year = doc.get("year", "")
            author_str = ", ".join(authors) if authors else ""

            if link:
                lines.append(f"### [{title}]({link})\n")
            else:
                lines.append(f"### {title}\n")

            meta_parts = []
            if author_str:
                meta_parts.append(f"**{author_str}**")
            meta_parts.append(f"({year})")
            meta_parts.append(f"— {doc.get('venue', '')}")
            lines.append(" ".join(meta_parts) + "\n")

            abstract = doc.get("abstract", "").strip()
            if abstract:
                lines.append(f"{abstract}\n")

            relevance = doc.get("relevance", "").strip()
            if relevance:
                lines.append(f"**NozKash relevance:** {relevance}\n")

            kw = format_keywords(doc)
            if kw:
                lines.append(f"**Keywords:** {kw}\n")

            lines.append("")

    # Not yet downloaded
    fetch_failures = PAPERS_DIR / "FETCH_FAILURES.md"
    if fetch_failures.exists():
        lines.append("## Not Yet Downloaded\n")
        lines.append("See [FETCH_FAILURES.md](FETCH_FAILURES.md) for papers needing manual download.\n")

    return "\n".join(lines)


def generate_standards_readme(
    rfc_docs: list[dict],
    eip_docs: list[dict] | None = None,
    bip_docs: list[dict] | None = None,
) -> str:
    """Generate standards/README.md from all standards sources."""
    lines = [GENERATED_HEADER]
    lines.append("# Standards & Specifications\n")
    lines.append(
        "Local copies of standards referenced by the NozKash protocol.\n"
        "See the `sources.yaml` files in each subdirectory for machine-readable metadata.\n"
    )

    # EIPs
    if eip_docs:
        lines.append("## EIPs (Ethereum Improvement Proposals)\n")
        for doc in eip_docs:
            link = best_link(doc, "eips")
            title = doc.get("title", "Untitled")
            eip_id = doc.get("id", "")

            lines.append(f"### [{eip_id}: {title}]({link})\n")

            abstract = doc.get("abstract", "").strip()
            if abstract:
                lines.append(f"{abstract}\n")

            relevance = doc.get("relevance", "").strip()
            if relevance:
                lines.append(f"**NozKash relevance:** {relevance}\n")

            kw = format_keywords(doc)
            if kw:
                lines.append(f"**Keywords:** {kw}\n")

            lines.append("")

    # BIPs
    if bip_docs:
        lines.append("## BIPs (Bitcoin Improvement Proposals)\n")
        for doc in bip_docs:
            link = best_link(doc, "bips")
            title = doc.get("title", "Untitled")
            bip_id = doc.get("id", "")

            lines.append(f"### [{bip_id}: {title}]({link})\n")

            abstract = doc.get("abstract", "").strip()
            if abstract:
                lines.append(f"{abstract}\n")

            relevance = doc.get("relevance", "").strip()
            if relevance:
                lines.append(f"**NozKash relevance:** {relevance}\n")

            kw = format_keywords(doc)
            if kw:
                lines.append(f"**Keywords:** {kw}\n")

            lines.append("")

    # RFCs
    lines.append("## RFCs & IETF Drafts\n")

    core_rfcs = [d for d in rfc_docs if not d.get("provenance")]
    pp_rfcs = [d for d in rfc_docs if d.get("provenance") == "forward-citation"]

    for doc in core_rfcs:
        local_files = doc.get("local_files", [])
        # Prefer generated .md, then .md from local_files, then .txt
        link = ""
        generated = doc.get("generated_md")
        if generated:
            link = f"rfcs/{generated}"
        else:
            for f in local_files:
                if f.endswith(".md") and not f.endswith(".bib"):
                    link = f"rfcs/{f}"
                    break
            if not link:
                for f in local_files:
                    if f.endswith(".txt"):
                        link = f"rfcs/{f}"
                        break

        title = doc.get("title", "Untitled")
        rfc_id = doc.get("id", "")

        if link:
            lines.append(f"### [{rfc_id}: {title}]({link})\n")
        else:
            lines.append(f"### {rfc_id}: {title}\n")

        abstract = doc.get("abstract", "").strip()
        if abstract:
            lines.append(f"{abstract}\n")

        relevance = doc.get("relevance", "").strip()
        if relevance:
            lines.append(f"**NozKash relevance:** {relevance}\n")

        kw = format_keywords(doc)
        if kw:
            lines.append(f"**Keywords:** {kw}\n")

        lines.append("")

    if pp_rfcs:
        lines.append("### Privacy Pass RFCs\n")
        lines.append("*IETF standards for anonymous token protocols — the closest standard-track analogue to NozKash.*\n")

        for doc in pp_rfcs:
            local_files = doc.get("local_files", [])
            generated = doc.get("generated_md")
            link = ""
            if generated:
                link = f"rfcs/{generated}"
            else:
                for f in local_files:
                    if f.endswith(".txt"):
                        link = f"rfcs/{f}"
                        break

            title = doc.get("title", "Untitled")
            rfc_id = doc.get("id", "")

            if link:
                lines.append(f"- [{rfc_id}: {title}]({link})")
            else:
                lines.append(f"- {rfc_id}: {title}")

            relevance = doc.get("relevance", "").strip()
            if relevance:
                lines.append(f"  — {relevance}")

            abstract = doc.get("abstract", "").strip()
            if abstract:
                lines.append(f"  {abstract}")

            lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate markdown indexes from YAML sources."
    )
    parser.add_argument(
        "--check", action="store_true",
        help="Verify indexes match YAML (exit 1 if stale)",
    )
    args = parser.parse_args()

    # Load all YAML sources
    papers_docs = load_yaml(PAPERS_DIR / "sources.yaml")

    rfc_yaml = RFCS_DIR / "sources.yaml"
    rfc_docs = load_yaml(rfc_yaml) if rfc_yaml.exists() else []

    eip_yaml = EIPS_DIR / "sources.yaml"
    eip_docs = load_yaml(eip_yaml) if eip_yaml.exists() else None

    bip_yaml = BIPS_DIR / "sources.yaml"
    bip_docs = load_yaml(bip_yaml) if bip_yaml.exists() else None

    # Generate indexes
    papers_readme = generate_papers_readme(papers_docs)
    standards_readme = generate_standards_readme(rfc_docs, eip_docs, bip_docs)

    papers_out = PAPERS_DIR / "README.md"
    standards_out = STANDARDS_DIR / "README.md"

    if args.check:
        stale = False
        for path, content in [(papers_out, papers_readme), (standards_out, standards_readme)]:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                print(f"  STALE  {path.relative_to(DOCS_SRC)}")
                stale = True
            else:
                print(f"  ok     {path.relative_to(DOCS_SRC)}")
        sys.exit(1 if stale else 0)

    papers_out.write_text(papers_readme, encoding="utf-8")
    print(f"  done  {papers_out.relative_to(DOCS_SRC)}")

    standards_out.write_text(standards_readme, encoding="utf-8")
    print(f"  done  {standards_out.relative_to(DOCS_SRC)}")


if __name__ == "__main__":
    main()
